### ISSUE TITLE
Test result graph

### ISSUE THREAD

**Issue by dansvend** [equinor/mad-project-hearing-test-client#109]
Previously the hearing test result graphs was generated as a PNG on the server side. Drawing the hearing test graphs should be done on the client for a better result after getting the result data from the API.

- [x] API needs to allow an endpoint to get the data for a graph ( /api/v1/me/tests/{id}/audiogram-data ) 
- [x] Add in the new graph component to the client, including hearing zone color bands on the image

Delivery Criteria : 

- Describe the tests needed to verify the change.

**Comment by SegarJJ** [comment]
API already has the endpoint.

**Comment by dansvend** [comment]
This is how it looks currently @SegarJJ 
![Simulator Screen Shot - iPhone 14 Pro Max - 2022-11-09 at 15 03 14](https://user-images.githubusercontent.com/47424077/200850627-271e5841-fb72-463f-8057-7437df35b983.png)

**Comment by SegarJJ** [comment]
Nice, lets roll with this for now.  we can come back at improving it in 2023

**Comment by dansvend** [comment]
@Sayyare 

This is ready for testing 👩‍🔬

```
-----------------------------
| Platform     | iOS        |
| Version      | 0.2.14     |
| Build number | 20221223.1 |
| Environment  | Test       |
-----------------------------
```

**Comment by Sayyare** [comment]
Took the test twice in test environment on V0.2.14 (20221223.1), but the app only shows the result of the left ear, compared previous results and it also looks like the results are not correct. @dansvend

**Comment by dansvend** [comment]
Thanks for testing @Sayyare 🙌 

If you didn't press the button after the sounds ate played during the test, your test result will be identical for both ears, meaning the data points will be on top of each other. I've made the blue(left ear) dots a little bigger than the red ones(right ear) for that reason so that you at least can see that there are blue points behind the red ones, like on the picture. Is that how it looked like? ![image](https://user-images.githubusercontent.com/47424077/209668260-d4579ed0-02ee-4d0c-b770-1d2faf514e4f.png)

**Comment by dansvend** [comment]
I saw you're screenshot now 🙌  I'll take a look at this, so you don't need to test more on this before I create a new build 🚀

**Comment by dansvend** [comment]
@Sayyare 

This is ready for testing 👩‍🔬 I think that verifying that all of your previous test results have a graph with three dots for for each ear (3 blue dots for left ear and 3 red for right ear) would be sufficient.

```
-----------------------------
| Platform     | iOS        |
| Version      | 0.2.14     |
| Build number | 20221227.1 |
| Environment  | Test       |
-----------------------------
```

**Comment by Sayyare** [comment]
Tested on V0.2.14 (201221227.1) in test environment, working as expected. @dansvend 😎
![image](https://user-images.githubusercontent.com/115469141/209807540-468b1e8e-70f2-465d-8597-7def44e81f65.png)

**Comment by dansvend** [comment]
Good news 😃 Thanks for testing @Sayyare 💪 

Merging this into the `main`-branch and setting Status to `🚦 Pending release`.
