### ISSUE TITLE
Handle unsent completed tests

### ISSUE THREAD

**Issue by SegarJJ** [equinor/mad-project-hearing-test-client#119]
If a user have a bad network connection when completing a hearing test the user will loose their hearing test.

The test needs to be saved on the device until the user is online again and can then send the test. A user should not be able to start a new test before sending in the unsent test.

### Things to design and implement

- [x] Design for manual resend on `TestResultScreen`
- [x] Design for showing unsent hearing test on homepage
- [x] Persist unsent hearingtest in redux store

### Example test cases

- [ ] Turn off WiFi during a hearing test and let it finish without network connection. When the test is finished it should lead you to a page where you get the option to either send your test again or navigate to the main menu. Enable WiFi and press on `Send`. The test should be sent and you can navigate to `Hovedmeny` where you should be able to start a new test.
- [ ] Turn off WiFi during a hearing test and let it finish without network connection. When the test is finished it should lead you to a page where you get the option to either send your test again or navigate to the main menu. Enable WiFi and press on `Hovedmeny`. You should not be able to start a new test, but should see how many unsent tests you have and be able to send it. After sending it you should be able to start a new test.

**Comment by dansvend** [comment]
@Sayyare @ntorsen

This is ready for testing 👩‍🔬

```
-----------------------------
| Platform     |        iOS |
| Version      |     0.2.13 |
| Build number | 20221031.1 |
| Environment  |       Test |
-----------------------------
```

**Comment by Sayyare** [comment]
All the requirements above are working as expected on version 0.2.13 in build  20221031.1

On offline it's not able to send the test, but it can be good to have a reminder that the test has been saved. 

@dansvend

**Comment by dansvend** [comment]
Thanks for testing and improvement proposal @Sayyare 🙏 I aded some text to let the user know that the test was saved but the test needs to be sent for evaluation.

This is ready for testing again 🧪 

```
-----------------------------
| Platform     |        iOS |
| Version      |     0.2.13 |
| Build number | 20221107.2 |
| Environment  |       Test |
-----------------------------
```

**Comment by Sayyare** [comment]
Working good on test environment on version 0.2.13 in build number 20221107.2. 👍

Is it possible to improve my results field? Even I sent the hearing test but there are only two blank attachments under my results. Or do you plan to create a new task for this issue?
![image](https://user-images.githubusercontent.com/115469141/200557006-df4cb168-ef96-4e82-aa11-fe48e6d4688b.png)

@dansvend

**Comment by dansvend** [comment]
Thanks for testing @Sayyare 🙏 

I will release this to production then 🚀 

I'm currently working on #109 to let the users see a result graph. It's really good that you come with improvement proposals - keep them coming 🙌
