### ISSUE TITLE
Requests to the MAD API fails

### ISSUE THREAD

**Issue by dansvend** [equinor/mad-project-hearing-test-client#126]
Requests to the MAD API does not work. For example fetching release notes and sending feedback in the app does not work.

**Comment by dansvend** [comment]
@ntorsen This is ready for testing in test environment🧪

- Version: 0.2.11
- Build number: 20221003.2

**Comment by dansvend** [comment]
Perfect, thank you for testing @ntorsen 🙏 

Release notes will only be displayed the first time you open the app for a specific version. But the fix was for the scopes for the API, so if the sending of feedback works, then release notes will also work.

To test release notes you can create a release note for version `0.2.11` and then delete the Hørselstest app and download it again and then the release note should be displayed when you open the app.

**Comment by ntorsen** [comment]
Release notes are working good as well, on iPhone and iPad
![image](https://user-images.githubusercontent.com/89014017/193758449-8853091e-601e-4e4b-95e7-55ad11493657.png)

@dansvend

**Comment by dansvend** [comment]
Super! Thanks for verifying @ntorsen 🙌
