### ISSUE TITLE
Use intended headset

### ISSUE THREAD

**Issue by dansvend** [equinor/mad-project-hearing-test-client#146]
Make sure the patients use the intended headset before they start a hearing test.

Barcode needs to be 01122022 which represents headset calibration date.

- [ ] #152

**Comment by SegarJJ** [comment]
user clicks to take a test

page 1: confirm the user is not sick ( or cancel out )

page 2:  to tell about the headset requirement and to start the scanning in the next step ( or cancel out )

page 3: is running the scanner.... start the scanner and continue until a code is scanned

page 4: give the user the result of the scanning ( good / bad ) 

page 5: tell user how to put on the headset ( or cancel out )

page 6: tell user about the left and right ear testing process, ( or cancel )

page 7: do the sound check clearly for each ear..... in bold.( or cancel out )

page 8: result of the sound check... then how to pause a test....( or cancel out )

page 9: are you ready to start the test?  ( or cancel out )

page 10: ( the test starts )

**Comment by SegarJJ** [comment]
@dansvend Are we truely blocked on this task or can we have a review with Ux after you have started ?

**Comment by dansvend** [comment]
@SegarJJ With so many changes in this issue it's gonna require a design.

**Comment by SegarJJ** [comment]
[See what you think here](https://www.figma.com/file/cBrC77iSYZ894atyBJV7O6vJ/H%C3%B8rselsoverv%C3%A5king?node-id=3496%3A74117&t=nn8iPHOVDu8BtMxK-4)

**Comment by SegarJJ** [comment]
HAhahaha, i hate the font picker in FIGMA . Please find the proper font! omg.

**Comment by dansvend** [comment]
@Sayyare 

This is ready for testing 👩‍🔬

```
-----------------------------
| Platform     |        iOS |
| Version      |     0.2.14 |
| Build number | 20221216.2 |
| Environment  |       Test |
-----------------------------
```

**Comment by Sayyare** [comment]
Tested in test environment on iOS in V0.2.14 20221216.2, all the features working as expected. 🎉
@dansvend

**Comment by SegarJJ** [comment]
two findings, you guys should consider how important it is to fix these: 

in the pretest pages, before the sound check, a user is not able to X out to escape the "im going to take a test" process

the second item is that the screen just after scanning... the button to continue says "scan"  when it should say something else.

**Comment by dansvend** [comment]
@Sayyare @SegarJJ 

Thanks for testing and giving feedback. I've implemented fixes for the two findings. A build is now ready for testing again 👩‍🔬

```
-----------------------------
| Platform     |        iOS |
| Version      |     0.2.14 |
| Build number | 20221219.2 |
| Environment  |       Test |
-----------------------------
```

**Comment by dansvend** [comment]
@Sayyare @SegarJJ 

Thanks for testing and giving feedback. I've implemented fixes for the two findings. A new build is ready for testing 👩‍🔬

```
-----------------------------
| Platform     |        iOS |
| Version      |     0.2.14 |
| Build number | 20221221.3 |
| Environment  |       Test |
-----------------------------
```

**Comment by Sayyare** [comment]
Working as expected in test environment on V0.2.14(20221221.3).  🎉 @dansvend 
The user able to X out to escape the test process and after scanning the button changes to "continue/fortsett".
