### ISSUE TITLE
Show correct message after test

### ISSUE THREAD

**Issue by dansvend** [equinor/mad-project-hearing-test-client#151]

**Comment by ofredstie** [comment]
@VetleW Do we have a design for all the potential "after test" pages that can be displayed after a user have completed a hearing test? 

In the code we have currently these pages:

![Image](https://github.com/equinor/mad-project-hearing-test-client/assets/3359842/d6663af7-fad3-4383-8d75-3eec4aa0f833)


![Image](https://github.com/equinor/mad-project-hearing-test-client/assets/3359842/2e75d9cf-fc08-4f90-9793-e957e6baf3d5)


The result can have one of these result states:


![Image](https://github.com/equinor/mad-project-hearing-test-client/assets/3359842/442650a9-6705-4dec-b070-37d64775d7de)


I created this [PR ](https://github.com/equinor/mad-project-hearing-test-client/pull/185/files) back in March, but I guess we should discuss if this change is sufficient

**Comment by VetleW** [comment]
@ofredstie Fant [disse](https://www.figma.com/file/cBrC77iSYZ894atyBJV7O6vJ/H%C3%B8rselsoverv%C3%A5king?type=design&node-id=3496-71315&t=03zPQo1MP0rmA2UB-4) sidene i Figma.

**Comment by ofredstie** [comment]
@SayyareHamit 

This is ready for testing 👩‍🔬 

How to test: 
- Start a new hearing test
- Set the phone in flight mode
- Verify that the result screen is similar to screenshot 1
- Turn off flight mode and start a new test
- Verify that the result screen is similar to screenshot 2 or screenshot 3
 (This code change should now show different result screens based on the test result and if the test was submitted or not)

```
-----------------------------
| Platform     | iOS          |
| Version      | 0.3.0        |
| Build number | 20230530.4   |
| Environment  | Test         |
-----------------------------
```

1. Screenshot 1

![Image](https://github.com/equinor/mad-project-hearing-test-client/assets/3359842/596443c3-3ccb-4903-9e76-917644132d0a)

2. Screenshot 2 - Result ok

![Image](https://github.com/equinor/mad-project-hearing-test-client/assets/3359842/2b562c71-0dbe-42d5-88c2-eb66ce97d7ef)

3. Screenshot 3 - Issue detected

![Image](https://github.com/equinor/mad-project-hearing-test-client/assets/3359842/78e5b3b6-acb4-41c5-a3c2-2c58acc44927)
