### ISSUE TITLE
Unable to start a test

### ISSUE THREAD

**Issue by dansvend** [equinor/mad-project-hearing-test-client#158]
It's not possible to get past the first page of `PreTestScreen` on an iPhone 7 since it's not possible to press the button to go to the next page.

![image](https://user-images.githubusercontent.com/47424077/210361006-00b0c2e7-7354-443b-ba57-3b2b0a04d4a3.png)

**Comment by Sayyare** [comment]
Tested together with Dan, it's possible to press the button to go to the next page. @dansvend 🐱‍💻
