### ISSUE TITLE
Release notes from Service Portal

### ISSUE THREAD

**Issue by dansvend** [equinor/mad-project-hearing-test-client#159]
Today we fetch Release Notes from Confluence. We should switch to a newer [commit](https://github.com/equinor/mad-expo-core/commit/251f781a6ea7ea2186212350bd6af04f2fa58214) of [mad-expo-core](https://github.com/equinor/mad-expo-core) where `ReleaseNoteScreen` fetches Release Notes from the Service Portal.

- [ ] Move all release notes in Confluence over to the Service Portal for all environments
- [ ] Delete release notes in Confluence

**Comment by dansvend** [comment]
@Sayyare 

This is ready for testing 👩‍🔬


```
-----------------------------
| Platform     | iOS        |
| Version      | 0.2.15     |
| Build number | 20230112.3 |
| Environment  | Test       |
-----------------------------
```

**Comment by Sayyare** [comment]
Working good as expected in Test environment, @dansvend 🐱‍🏍

**Comment by dansvend** [comment]
Depending on #160 and therefore can not be released until that's fixed.
