### ISSUE TITLE
Application Insights

### ISSUE THREAD

**Issue by dansvend** [equinor/mad-project-hearing-test-client#160]
Add Application Insights from [mad-expo-core](https://github.com/equinor/mad-expo-core).

**Comment by dansvend** [comment]
@Sayyare 

This is ready for testing 👩‍🔬 The only logging events that's added are the most basic ones from LoginScreen, like:
- Application ACTIVE
- Application BACKGROUND
- Application STARTED
- Authentication
- Authentication DEMO MODE
- Authentication AUTOMATIC


```
-----------------------------
| Platform     | iOS        |
| Version      | 0.2.15     |
| Build number | 20230112.2 |
| Environment  | Test       |
-----------------------------
```

**Comment by dansvend** [comment]
@Sayyare 

This is ready for testing 👩‍🔬 The only logging events that's added are the most basic ones from LoginScreen, like:
- Application ACTIVE
- Application BACKGROUND
- Application STARTED
- Authentication
- Authentication DEMO MODE
- Authentication AUTOMATIC


```
-----------------------------
| Platform     | iOS        |
| Version      | 0.2.15     |
| Build number | 20230112.2 |
| Environment  | Test       |
-----------------------------
```

**Comment by dansvend** [comment]
After having a chat with Tormod the doubled count of events triggered is a known issue but does not affect the reason we have use Application Insights, which is to be able to debug failed requests. I've made an [issue](https://github.com/equinor/mad-expo-core/issues/132) for this in mad-expo-core. Since this code change is required to be able to implement #159 I think it should be okay to merge it in.

**Comment by Sayyare** [comment]
Tested in build 20230112.2, the application is working as expected. @dansvend 🐱‍🏍
 I deleted and reinstall the application, it's not able to see "Application Started",
![image](https://user-images.githubusercontent.com/115469141/218423219-b449653a-8e0a-415b-be39-726a011de042.png)

**Comment by dansvend** [comment]
Nice! It seems like the `Application STARTED` is catched by a filter which means it wont show up.

```JSX
// appInsights.ts in mad-expo-core

export const track = (
  eventName: metricKeys,
  eventStatus?: metricStatus,
  extraText?: string,
  extraData?: ICustomProperties
) => {
  const eventString = `${eventName} ${eventStatus || ''}. ${extraText || ''}`;
  if (excludeLogFilter(eventString, ["Ping", "ServiceMessage,", "STARTED"])) return;

  trackEvent({ name: eventString }, extraData);
  if (appInsightsLongTermLog) {
    trackEventLongTerm({ name: eventString }, extraData);
  }
};
```
