### ISSUE TITLE
React Component Inspector is not working

### ISSUE THREAD

**Issue by dansvend** [equinor/mad-project-hearing-test-client#164]
React Component inspector in React Native Debugger is not working

To fix the React Tree in the React Native Debugger you can follow this procedure:
1. Delete the following from `package.json`:
```JSON
  "overrides": {
    "react-native": {
      "react-devtools-core": "4.14.0"
    }
  },
```
2. Run:
```
npm i
```
3. Commit the new `package.json` and `package-lock.json`

**Comment by dansvend** [comment]
@Sayyare 

This is ready for testing 👩‍🔬


```
-----------------------------
| Platform     | iOS        |
| Version      | 0.2.15     |
| Build number | 20230112.4 |
| Environment  | Test       |
-----------------------------
```

**Comment by Sayyare** [comment]
Working good in Test environment, @dansvend 🐱‍💻
