### ISSUE TITLE
Time and date for list of test results

### ISSUE THREAD

**Issue by ofredstie** [equinor/mad-project-hearing-test-client#182]
When a user have performed multiple tests on the same day it is not possible to see which is which due to only the date being listed. 

![Simulator Screen Shot - iPhone 14 Pro Max - 2023-03-23 at 08 30 33](https://user-images.githubusercontent.com/3359842/227134254-873c6470-d465-47b5-9fcb-44e857ed2721.png)

Adding hours and minutes to the listing would solve this issue.

**Comment by ofredstie** [comment]
![Image](https://user-images.githubusercontent.com/3359842/233283552-b957c038-8d8e-4c27-b204-83cce7972a9b.png)


![Image](https://user-images.githubusercontent.com/3359842/233283585-d034619f-7907-43e7-bebc-0b07b205db42.png)

**Comment by SayyareHamit** [comment]
Works good in Test environment on build 20230503.5 @ofredstie  😎
