### ISSUE TITLE
App crashes when viewing results

### ISSUE THREAD

**Issue by dansvend** [equinor/mad-project-hearing-test-client#196]
The app sometimes crash when pressing `Se resultat` on the screen displayed right after finishing a hearing test.

**Comment by ofredstie** [comment]
![Image](https://user-images.githubusercontent.com/3359842/236820839-f4c4e439-a705-4554-b4db-2199e41b7d29.png)
![Image](https://user-images.githubusercontent.com/3359842/236820838-fa5bbc5e-ea90-41e1-a0cb-5922698d60ec.png)

**Comment by ofredstie** [comment]
![Image](https://github.com/equinor/mad-project-hearing-test-client/assets/3359842/2084fb30-b1db-415c-bbbd-5cc03514e013)

**Comment by ofredstie** [comment]
[testflight_feedback.zip](https://github.com/equinor/mad-project-hearing-test-client/files/11429845/testflight_feedback.zip)

**Comment by ofredstie** [comment]
![Image](https://github.com/equinor/mad-project-hearing-test-client/assets/3359842/bec6e3bb-0016-4c9e-9aa4-e6cc4759a79d)



![Image](https://github.com/equinor/mad-project-hearing-test-client/assets/3359842/124af90c-c218-4a94-893c-b128e8c37062)

**Comment by ofredstie** [comment]
How to reproduce: Click on "Se resultat" immediately after test is completed will result in the app crashing. If the user wait a few seconds the modal will be displayed correctly.

**Comment by VetleW** [comment]
[Here](https://www.figma.com/file/cBrC77iSYZ894atyBJV7O6vJ/H%C3%B8rselsoverv%C3%A5king?type=design&node-id=3979-85776&t=7VArhj6L1HgHGLMt-4) is a prototype of a possible fix

**Comment by ofredstie** [comment]
After discussions with @VetleW we agreed on the following fix:
- Button text will be "Analyserer..." while the data is being loaded
- Button is disabled while the data is being loaded

https://github.com/equinor/mad-project-hearing-test-client/assets/3359842/093b1d6c-c8db-49a4-8283-7bf1de0de2bc

**Comment by ofredstie** [comment]
![Image](https://github.com/equinor/mad-project-hearing-test-client/assets/3359842/ca00a77c-33c3-4b50-93ee-e6d017e589c4)

**Comment by ofredstie** [comment]
@SayyareHamit 

This is ready for testing 👩‍🔬 

How to test: 
- Start a new hearing test
- Immediately when the test is over verify that the "Se resultat" button is replaced by a progress spinner and that the button is disabled. 
- After a few seconds the spinner should be replaced by "Se resultat" and you should now be able to click on it and see your result. 
- The app should not crash when clicking on "Se resultat" 

```
-----------------------------
| Platform     | iOS        |
| Version      | 0.3.0      |
| Build number | 220230525.2 |
| Environment  | Test       |
-----------------------------
```
