### ISSUE TITLE
Progress bar not reset after selecting "Start på ny"

### ISSUE THREAD

**Issue by ofredstie** [equinor/mad-project-hearing-test-client#212]
After resetting the test the progress bar remains at the previous "progress" state

![Skjermbilde 2023-05-24 kl  14 34 21](https://github.com/equinor/mad-project-hearing-test-client/assets/3359842/c224ff64-6b2e-4dcb-9fe3-637a05ad142c)

**Comment by ofredstie** [comment]
Test also continues after the progress bar has reached 100%



![Image](https://github.com/equinor/mad-project-hearing-test-client/assets/3359842/f77a17d4-f4fe-49d6-8ed1-db6d37eaf748)

**Comment by ofredstie** [comment]
How to test: 
- Start a new hearing test
- Let the test run until progress bar have reached approx. halfway
- Click on pause
- Select "Start på ny" to restart test
- Verify that the progress bar is reset to 0%
- Verify that the test does not continue after progress bar have reached 100%

**Comment by SayyareHamit** [comment]
Couldn't hear the sound when I restart the test. @ofredstie 
Can you please look for the issue?

**Comment by ofredstie** [comment]
@SayyareHamit I've tested this from the main branch now and it is the same problem there. 

I have therefore created a new [issue](https://github.com/equinor/mad-project-hearing-test-client/issues/218) for this specific bug.

I think that you can commence with the test of this issue

**Comment by SayyareHamit** [comment]
Progress bar reset after starting the new test, works good. @ofredstie ✔
